import { Origin, RiskClass, ApplicationType, Rule, DocScenario } from "../types";

export const DEFAULT_MDPASS_RULES: any = {
  "version": "2.0",
  "law_reference": "醫療器材許可證核發與登錄及年度申報準則第六條附表二",
  "last_updated": "2024-05-22",
  "description": "本規則檔案供 MDPASS 系統進行自動化法規判定，支援自定義上傳與修改。",
  "base_docs": {
    "D1": "醫療器材查驗登記申請書",
    "D2": "標籤、說明書或包裝擬稿",
    "D3": "醫療器材商許可執照影本",
    "D4": "出產國許可製售證明正本 (FSC)",
    "D5": "國外原廠授權登記書正本 (LOA)",
    "D6": "品質管理系統證明文件 (QMS/GMP)",
    "D7": "臨床前測試、規格檢驗方法、原始紀錄及成績書",
    "D8": "產品結構、材料、規格、性能、用途、圖樣資料",
    "D9": "臨床證據資料 (Clinical Evidence)",
    "D10": "發生游離輻射器材之輻射防護安全資料",
    "D11": "醫療器材安全性與功效性基本規範及技術文件摘要 (STED)",
    "D12": "原廠同一產品不同品名之說明函正本",
    "D13": "原核准之標籤、說明書或包裝影本 (蓋核定章)",
    "D14": "原核准之醫療器材許可證影本",
    "D15": "其他經中央主管機關指定之文件",
    "D16": "樣品送驗 (依公告品項)",
    "D17": "中文說明書詳細譯稿及產品外觀彩色照片",
    "D18": "委託製造契約書 (受託/委託方關係證明)",
    "D19": "產地為中國之經濟部准許輸入證明文件",
    "D20": "動物來源(牛羊)原料來源管制說明及證明",
    "D21": "商標註冊相關資料 (若品名冠有商標)",
    "D22": "軟體確效報告 (Software Validation)",
    "D23": "生物相容性報告 (Biocompatibility)",
    "D24": "電氣安全及電磁相容性報告 (Safety/EMC)",
    "D25": "滅菌確效報告 (Sterilization Validation)",
    "D26": "安定性試驗報告 (Stability Data)",
    "D27": "類似品比較暨臨床前測試資料符合性聲明書",
    "D28": "基本規範符合性聲明書 (EP Check List)",
    "D29": "臨床前測試資料切結書 (特定公告品項)",
    "D30": "藥品優良製造規範 (GMP) 證明文件 (藥轉醫專用)"
  },
  "scenarios": [
    { "id": "S01", "name": "國產二級標準案", "conditions": { "origin": "DOMESTIC", "risk": "CLASS_2", "path": "STANDARD" }, "req": ["D1","D2","D3","D6","D8","D15"], "cond": ["D7","D9","D10","D16"] },
    { "id": "S02", "name": "輸入二級標準案", "conditions": { "origin": "IMPORT", "risk": "CLASS_2", "path": "STANDARD" }, "req": ["D1","D2","D3","D4","D5","D6","D8"], "cond": ["D7","D9","D10","D11","D15","D16"] },
    { "id": "S03", "name": "國產三級標準案", "conditions": { "origin": "DOMESTIC", "risk": "CLASS_3", "path": "STANDARD" }, "req": ["D1","D2","D3","D6","D7","D8","D11"], "cond": ["D9","D10","D15","D16"] },
    { "id": "S04", "name": "輸入三級標準案", "conditions": { "origin": "IMPORT", "risk": "CLASS_3", "path": "STANDARD" }, "req": ["D1","D2","D3","D4","D5","D6","D7","D8","D11"], "cond": ["D9","D10","D15","D16"] },
    { "id": "S05", "name": "國產二級同一產品不同品名", "conditions": { "origin": "DOMESTIC", "risk": "CLASS_2", "path": "DIFF_NAME" }, "req": ["D1","D2","D3","D12","D13","D14"], "cond": ["D15"] },
    { "id": "S06", "name": "輸入二級同一產品不同品名", "conditions": { "origin": "IMPORT", "risk": "CLASS_2", "path": "DIFF_NAME" }, "req": ["D1","D2","D3","D4","D5","D12","D13","D14"], "cond": ["D15"] },
    { "id": "S07", "name": "國產三級同一產品不同品名", "conditions": { "origin": "DOMESTIC", "risk": "CLASS_3", "path": "DIFF_NAME" }, "req": ["D1","D2","D3","D12","D13","D14"], "cond": ["D15"] },
    { "id": "S08", "name": "輸入三級同一產品不同品名", "conditions": { "origin": "IMPORT", "risk": "CLASS_3", "path": "DIFF_NAME" }, "req": ["D1","D2","D3","D4","D5","D12","D13","D14"], "cond": ["D15"] },
    { "id": "S09", "name": "專供外銷(國產)", "conditions": { "origin": "DOMESTIC", "path": "EXPORT_ONLY" }, "req": ["D1","D3","D6","D15"], "cond": [] },
    { "id": "S10", "name": "專供外銷(輸入)", "conditions": { "origin": "IMPORT", "path": "EXPORT_ONLY" }, "req": ["D1","D3","D6","D15"], "cond": [] },
    { "id": "S11", "name": "國產二級+中國產地", "conditions": { "origin": "DOMESTIC", "risk": "CLASS_2", "is_china": true }, "req": ["D1","D2","D3","D6","D8","D19"], "cond": ["D7"] },
    { "id": "S12", "name": "輸入二級+中國產地", "conditions": { "origin": "IMPORT", "risk": "CLASS_2", "is_china": true }, "req": ["D1","D2","D3","D4","D5","D6","D8","D19"], "cond": ["D7"] },
    { "id": "S13", "name": "國產三級+中國產地", "conditions": { "origin": "DOMESTIC", "risk": "CLASS_3", "is_china": true }, "req": ["D1","D2","D3","D6","D7","D8","D11","D19"], "cond": ["D9"] },
    { "id": "S14", "name": "輸入三級+中國產地", "conditions": { "origin": "IMPORT", "risk": "CLASS_3", "is_china": true }, "req": ["D1","D2","D3","D4","D5","D6","D7","D8","D11","D19"], "cond": ["D9"] },
    { "id": "S15", "name": "國產二級+輻射醫材", "conditions": { "origin": "DOMESTIC", "risk": "CLASS_2", "is_rad": true }, "req": ["D1","D2","D3","D6","D8","D10"], "cond": ["D7"] },
    { "id": "S16", "name": "輸入二級+輻射醫材", "conditions": { "origin": "IMPORT", "risk": "CLASS_2", "is_rad": true }, "req": ["D1","D2","D3","D4","D5","D6","D8","D10"], "cond": ["D7"] },
    { "id": "S17", "name": "國產三級+輻射醫材", "conditions": { "origin": "DOMESTIC", "risk": "CLASS_3", "is_rad": true }, "req": ["D1","D2","D3","D6","D7","D8","D10","D11"], "cond": ["D9"] },
    { "id": "S18", "name": "輸入三級+輻射醫材", "conditions": { "origin": "IMPORT", "risk": "CLASS_3", "is_rad": true }, "req": ["D1","D2","D3","D4","D5","D6","D7","D8","D10","D11"], "cond": ["D9"] },
    { "id": "S19", "name": "輸入二級+動物組織", "conditions": { "origin": "IMPORT", "risk": "CLASS_2", "is_animal": true }, "req": ["D1","D2","D3","D4","D5","D6","D8","D20"], "cond": ["D7"] },
    { "id": "S20", "name": "輸入三級+動物組織", "conditions": { "origin": "IMPORT", "risk": "CLASS_3", "is_animal": true }, "req": ["D1","D2","D3","D4","D5","D6","D7","D8","D11","D20"], "cond": ["D9"] },
    { "id": "S21", "name": "二級簡化(7-2-1)標準", "conditions": { "risk": "CLASS_2", "method": "SIMPLIFIED_721" }, "req": ["D1","D2","D3","D6","D8","D11","D28"], "cond": ["D7"] },
    { "id": "S22", "name": "二級簡化(7-2-2)切結", "conditions": { "risk": "CLASS_2", "method": "SIMPLIFIED_722" }, "req": ["D1","D2","D3","D6","D8","D29"], "cond": ["D7"] },
    { "id": "S23", "name": "二級簡化(7-3)類似品聲明", "conditions": { "risk": "CLASS_2", "method": "SIMPLIFIED_73" }, "req": ["D1","D2","D3","D6","D8","D27"], "cond": ["D7"] },
    { "id": "S24", "name": "三級全球首創(無類似品)", "conditions": { "risk": "CLASS_3", "has_similar": false }, "req": ["D1","D2","D3","D6","D7","D8","D9","D11"], "cond": ["D4"] },
    { "id": "S25", "name": "國產儀器類醫材", "conditions": { "origin": "DOMESTIC", "category": "INSTRUMENT" }, "req": ["D1","D2","D3","D6","D8","D24"], "cond": ["D7"] },
    { "id": "S26", "name": "輸入儀器類醫材", "conditions": { "origin": "IMPORT", "category": "INSTRUMENT" }, "req": ["D1","D2","D3","D4","D5","D6","D8","D24"], "cond": ["D7"] },
    { "id": "S27", "name": "國產二級+軟體(SaMD)", "conditions": { "origin": "DOMESTIC", "risk": "CLASS_2", "is_software": true }, "req": ["D1","D2","D3","D6","D8","D22"], "cond": ["D7"] },
    { "id": "S28", "name": "輸入二級+軟體(SaMD)", "conditions": { "origin": "IMPORT", "risk": "CLASS_2", "is_software": true }, "req": ["D1","D2","D3","D4","D5","D6","D8","D22"], "cond": ["D7"] },
    { "id": "S29", "name": "國產三級+軟體(SaMD)", "conditions": { "origin": "DOMESTIC", "risk": "CLASS_3", "is_software": true }, "req": ["D1","D2","D3","D6","D7","D8","D11","D22"], "cond": ["D9"] },
    { "id": "S30", "name": "輸入三級+軟體(SaMD)", "conditions": { "origin": "IMPORT", "risk": "CLASS_3", "is_software": true }, "req": ["D1","D2","D3","D4","D5","D6","D7","D8","D11","D22"], "cond": ["D9"] },
    { "id": "S31", "name": "滅菌類醫材", "conditions": { "is_sterile": true }, "req": ["D25"], "cond": ["D7"] },
    { "id": "S32", "name": "藥轉醫過渡案", "conditions": { "is_med_to_md": true }, "req": ["D1","D2","D3","D30"], "cond": ["D6"] },
    { "id": "S33", "name": "委託製造(國產)", "conditions": { "origin": "DOMESTIC", "is_contract": true }, "req": ["D1","D3","D6","D18"], "cond": [] },
    { "id": "S34", "name": "無類似品二級(9-4)醫材", "conditions": { "risk": "CLASS_2", "has_similar": false }, "req": ["D1","D2","D3","D6","D8","D9"], "cond": ["D7"] },
    { "id": "S35", "name": "冠有商標之醫材", "conditions": { "has_trademark": true }, "req": ["D21"], "cond": [] },
    { "id": "S36", "name": "二級具類似品(9-3)免臨床", "conditions": { "risk": "CLASS_2", "has_similar": true }, "req": ["D1","D2","D3","D6","D8"], "cond": ["D9"] },
    { "id": "S37", "name": "輸入案+外文非英文", "conditions": { "origin": "IMPORT", "lang_english": false }, "req": ["D17"], "cond": [] },
    { "id": "S38", "name": "安定性要求醫材", "conditions": { "need_stability": true }, "req": ["D26"], "cond": ["D8"] },
    { "id": "S39", "name": "生物相容性要求醫材", "conditions": { "need_biocompat": true }, "req": ["D23"], "cond": ["D7"] },
    { "id": "S40", "name": "三級案+臨床評估報告", "conditions": { "risk": "CLASS_3", "method": "CER" }, "req": ["D9","D11"], "cond": [] },
    { "id": "S41", "name": "體外診斷二級標準", "conditions": { "category": "IVD", "risk": "CLASS_2" }, "req": ["D1","D2","D3","D6","D8"], "cond": ["D7"] },
    { "id": "S42", "name": "體外診斷三級標準", "conditions": { "category": "IVD", "risk": "CLASS_3" }, "req": ["D1","D2","D3","D6","D7","D8","D11"], "cond": ["D9"] },
    { "id": "S43", "name": "組合產品(醫材主體)", "conditions": { "is_combination": true }, "req": ["D1","D2","D8","D15"], "cond": ["D9"] },
    { "id": "S44", "name": "國外已上市三級(簡化)", "conditions": { "risk": "CLASS_3", "us_eu_approved": true }, "req": ["D4","D5","D7","D11"], "cond": ["D9"] },
    { "id": "S45", "name": "需檢驗品項送驗案", "conditions": { "need_testing": true }, "req": ["D16"], "cond": [] },
    { "id": "S46", "name": "同一產品增列規格", "conditions": { "path": "ADD_SPEC" }, "req": ["D1","D2","D8","D14"], "cond": ["D7"] },
    { "id": "S47", "name": "二級類似品(有種族差異性)", "conditions": { "risk": "CLASS_2", "ethnic_diff": true }, "req": ["D9"], "cond": [] },
    { "id": "S48", "name": "輸入總公司授權案", "conditions": { "origin": "IMPORT", "auth_type": "HQ" }, "req": ["D5"], "cond": [] },
    { "id": "S49", "name": "藥商執照變更併案", "conditions": { "need_license_change": true }, "req": ["D3"], "cond": [] },
    { "id": "S50", "name": "緊急授權(EUA)案", "conditions": { "path": "EUA" }, "req": ["D1","D2","D8","D15"], "cond": ["D6"] }
  ]
};

export const ADVANCED_CONFLICT_RULES: any = {
  "ruleset_name": "TFDA 醫材查驗登記智慧審核規則庫",
  "version": "2.1",
  "rules": [
    { "id": "C01", "name": "FSC 效期判定", "logic": "D4_issue_date < today - 730 days", "msg": "FSC 已超過 2 年效期，依準則規定無效。", "severity": "ERROR" },
    { "id": "C02", "name": "QMS 效期預警", "logic": "D9_expiry_date < today + 180 days", "msg": "QMS 證明文件將於半年內過期，建議更換。", "severity": "WARNING" },
    { "id": "C03", "name": "代理商一致性", "logic": "D5_agent != D3_owner", "msg": "授權書(LOA)代理商與藥商執照持有人不符。", "severity": "ERROR" },
    { "id": "C04", "name": "產地地址匹配", "logic": "D4_mfg_addr != D9_mfg_addr", "msg": "FSC 地址與 QMS 廠址字串不一致，請核對。", "severity": "WARNING" },
    { "id": "C05", "name": "三級案 STED 強制性", "logic": "risk == 'CLASS_3' and not exists(D11)", "msg": "第三等級案件必須提供 STED 技術文件摘要。", "severity": "ERROR" },
    { "id": "C06", "name": "無菌報告衝突", "logic": "attr_sterile == true and not exists(D25)", "msg": "宣稱為無菌產品，但缺少滅菌確效報告。", "severity": "ERROR" },
    { "id": "C07", "name": "中國產地准許證", "logic": "origin_country == 'CHINA' and not exists(D19)", "msg": "產地為中國，應檢附經濟部輸入許可證明。", "severity": "ERROR" },
    { "id": "C08", "name": "讓與案共同聲明", "logic": "change_type == 'TRANSFER' and not exists(D16)", "msg": "讓與案件必須由雙方共同簽署讓與聲明書。", "severity": "ERROR" },
    { "id": "C09", "name": "遺失補發邏輯錯誤", "logic": "path == 'REISSUE' and exists(D3)", "msg": "既申請遺失補發，系統不應偵測到原許可證正本。", "severity": "CRITICAL" },
    { "id": "C10", "name": "軟體確效報告", "logic": "attr_software == true and not exists(D22)", "msg": "產品包含軟體功能，缺少軟體確效報告(Validation)。", "severity": "ERROR" },
    { "id": "C11", "name": "FSC 語言譯本", "logic": "D4_lang == 'OTHER' and not exists(D29)", "msg": "FSC 非英日文，應檢附核證之中文譯本。", "severity": "WARNING" },
    { "id": "C12", "name": "變更案標籤對照", "logic": "change_label == true and (not exists(D4) or not exists(D5))", "msg": "標籤變更需同時提供原核定本與擬變更稿對照。", "severity": "ERROR" },
    { "id": "C13", "name": "生物相容性完整性", "logic": "attr_implant == true and not exists(D23)", "msg": "植入性產品必須檢附生物相容性測試報告。", "severity": "CRITICAL" },
    { "id": "C14", "name": "輻射防護資料", "logic": "attr_radiation == true and not exists(D13)", "msg": "放射性醫材必須提供輻射防護安全資料。", "severity": "ERROR" },
    { "id": "C15", "name": "電氣安全測試", "logic": "category == 'INSTRUMENT' and not exists(D24)", "msg": "儀器類醫材必須檢附電氣安全(IEC 60601)報告。", "severity": "ERROR" },
    { "id": "C16", "name": "變更說明函日期", "logic": "D14_date > today", "msg": "原廠說明函日期為未來時間，請檢查輸入格式。", "severity": "ERROR" },
    { "id": "C17", "name": "IVD 技術資料", "logic": "category == 'IVD' and risk == 'CLASS_3' and not exists(D24)", "msg": "三級 IVD 應提供完整技術性資料。", "severity": "ERROR" },
    { "id": "C18", "name": "門牌整編排除", "logic": "change_addr == true and rezoning == true and exists(D9)", "msg": "若為門牌整編，可豁免新廠 QMS 證明。", "severity": "INFO" },
    { "id": "C19", "name": "藥轉醫 GMP 替代", "logic": "med_to_md == true and exists(D30)", "msg": "藥轉醫案件，系統已接受以 GMP 證明替代 QMS。", "severity": "INFO" },
    { "id": "C20", "name": "樣品送驗狀態", "logic": "testing_needed == true and not exists(D27)", "msg": "依規定需送驗，請上傳檢驗費與樣品明細。", "severity": "ERROR" },
    { "id": "C21", "name": "LOA 授權範圍", "logic": "D5_scope != 'FULL' and change_spec == true", "msg": "授權書範圍不完整，可能無法支援規格變更。", "severity": "WARNING" },
    { "id": "C22", "name": "二級類似品聲明", "logic": "risk == 'CLASS_2' and path == 'SIMPLIFIED' and not exists(D27)", "msg": "二級簡化路徑應附類似品比較暨符合性聲明。", "severity": "ERROR" },
    { "id": "C23", "name": "原廠地址國別匹配", "logic": "D4_country != D9_country", "msg": "FSC 生產國與 QMS 登錄國別不一致。", "severity": "CRITICAL" },
    { "id": "C24", "name": "臨床評價報告(CER)", "logic": "risk == 'CLASS_3' and not exists(D9_clinical)", "msg": "三級醫材應包含臨床評價報告(CER)或臨床數據。", "severity": "WARNING" },
    { "id": "C25", "name": "委託製造關係", "logic": "is_contract == true and not exists(D28)", "msg": "屬委託製造，應檢附委託製造契約書影本。", "severity": "ERROR" },
    { "id": "C26", "name": "穩定性試驗效期", "logic": "D26_shelf_life != label_shelf_life", "msg": "穩定性報告年限與標籤宣稱效期不符。", "severity": "ERROR" },
    { "id": "C27", "name": "IVD 儲存條件", "logic": "category == 'IVD' and not exists(D45_storage)", "msg": "IVD 產品應明確提供儲存條件資料(D45)。", "severity": "WARNING" },
    { "id": "C28", "name": "讓與日期邏輯", "logic": "transfer_date < D3_issue_date", "msg": "讓與日期早於許可證核發日期，邏輯有誤。", "severity": "CRITICAL" },
    { "id": "C29", "name": "三級效能縮減", "logic": "risk == 'CLASS_3' and change_intended_use == true", "msg": "三級效能變更審查較嚴，需確認 D12 是否詳盡。", "severity": "INFO" },
    { "id": "C30", "name": "標籤彩色照片", "logic": "D5_color == false", "msg": "標籤擬稿建議提供彩色版，以利外觀比對。", "severity": "WARNING" },
    { "id": "C31", "name": "專供外銷標籤豁免", "logic": "path == 'EXPORT' and exists(D2)", "msg": "專供外銷案不需標籤擬稿，系統已自動排除。", "severity": "INFO" },
    { "id": "C32", "name": "品名商標核對", "logic": "brand_name == true and not exists(D21)", "msg": "品名含商標者，建議提供商標註冊資料。", "severity": "WARNING" },
    { "id": "C33", "name": "二級無類似品臨床", "logic": "risk == 'CLASS_2' and similar == false and not exists(D9)", "msg": "二級無類似品案件應加強檢附臨床數據。", "severity": "ERROR" },
    { "id": "C34", "name": "代理權移轉遺漏", "logic": "path == 'LOA_CHANGE' and not exists(D8)", "msg": "代理權移轉案件必須上傳新授權書。", "severity": "ERROR" },
    { "id": "C35", "name": "QMS 廠名相似度", "logic": "D9_factory_name != D4_factory_name", "msg": "QMS 廠名與 FSC 廠名不精確匹配，請確認。", "severity": "WARNING" },
    { "id": "C36", "name": "中文品名重複檢查", "logic": "name_cn == existing_database", "msg": "該中文品名已被其他許可證佔用，請修改。", "severity": "ERROR" },
    { "id": "C37", "name": "英文品名拼寫衝突", "logic": "name_en != D4_name_en", "msg": "英文品名與產地證明(FSC)上名稱不符。", "severity": "ERROR" },
    { "id": "C38", "name": "動物來源管制", "logic": "attr_animal == true and not exists(D20)", "msg": "含牛羊組織者，需附來源管制說明(D20)。", "severity": "CRITICAL" },
    { "id": "C39", "name": "體外診斷檢體類型", "logic": "category == 'IVD' and specimen_type == null", "msg": "請於申請書標明 IVD 之檢體類型。", "severity": "ERROR" },
    { "id": "C40", "name": "單一包裝多型號", "logic": "multi_model == true and not exists(D15)", "msg": "多型號變更，必須檢附詳盡之型號對照表。", "severity": "ERROR" },
    { "id": "C41", "name": "說明函授權有效性", "logic": "D14_sign_title == 'LOW'", "msg": "原廠說明函簽署人職位過低，可能不被採認。", "severity": "WARNING" },
    { "id": "C42", "name": "外文授權書核證", "logic": "D5_notarized == false", "msg": "國外授權書應經我國駐外館處驗證。", "severity": "ERROR" },
    { "id": "C43", "name": "合併規格變更技術要求", "logic": "change_spec == true and change_intended_use == true", "msg": "合併效能與規格變更，技術文件應整合說明。", "severity": "INFO" },
    { "id": "C44", "name": "原核定標籤污損", "logic": "path == 'LABEL_DEFACED' and not exists(D4)", "msg": "污損換發必須檢附原污損之核定標籤正本。", "severity": "ERROR" },
    { "id": "C45", "name": "滅菌方式變更報告", "logic": "change_sterile_method == true and not exists(D25)", "msg": "變更滅菌方式應重新提交滅菌確效驗證。", "severity": "ERROR" },
    { "id": "C46", "name": "EP Check List 缺項", "logic": "risk == 'CLASS_3' and exists(D11) and D28_ep_list == false", "msg": "STED 內應包含基本規範(EP)符合性清單。", "severity": "WARNING" },
    { "id": "C47", "name": "臨床前試驗原始數據", "logic": "D7_raw_data == false", "msg": "臨床前測試僅有摘要無原始紀錄，可能被退件。", "severity": "WARNING" },
    { "id": "C48", "name": "變更不涉原核准事項", "logic": "change_item == 'OTHER' and exists(D15)", "msg": "其他變更應檢附變更前後內容比較表。", "severity": "INFO" },
    { "id": "C49", "name": "二級案簡化切結", "logic": "path == 'SIMPLIFIED_722' and not exists(D29)", "msg": "依 7-2-2 辦理者應檢附臨床前測試資料切結書。", "severity": "ERROR" },
    { "id": "C50", "name": "總體邏輯一致性檢查", "logic": "errors_count > 10", "msg": "本案衝突過多，請重新檢視案件完整性。", "severity": "CRITICAL" }
  ]
};

